// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bL97kH9Dzecu8g2MxMGBSt
// Component: FrY64Kg3_uc7
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import NavBar from "../../NavBar" // plasmic-import: XWbHcDJXryxF/component
import Button from "../../Button" // plasmic-import: EDRR_UWJpEhW/component
import Price from "../../Price" // plasmic-import: akI3guSsN0EL/component
import Separator from "../../Separator" // plasmic-import: zJE6f4pfA7HN/component
import ProductCard from "../../ProductCard" // plasmic-import: WvhVlBnfrFth/component
import Footer from "../../Footer" // plasmic-import: dQk1N0a__grK/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen" // plasmic-import: wjkIUuh2R8iq/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css" // plasmic-import: bL97kH9Dzecu8g2MxMGBSt/projectcss
import * as sty from "./PlasmicItem.module.css" // plasmic-import: FrY64Kg3_uc7/css
import Icon24Icon from "./icons/PlasmicIcon__Icon24" // plasmic-import: icXeXfeZhCw6/icon
import Icon25Icon from "./icons/PlasmicIcon__Icon25" // plasmic-import: saAQIvivn_ww/icon
import Icon26Icon from "./icons/PlasmicIcon__Icon26" // plasmic-import: BKMCJHsDJp4l/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5" // plasmic-import: T-JTXcMDzEWg/icon
import Icon22Icon from "./icons/PlasmicIcon__Icon22" // plasmic-import: 7JOyoRQGqGVQ/icon
import Icon21Icon from "./icons/PlasmicIcon__Icon21" // plasmic-import: GIhjieRuC-DB/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20" // plasmic-import: eMZOJ7TiEN_c/icon

export const PlasmicItem__VariantProps = new Array()

export const PlasmicItem__ArgProps = new Array(
  "container42",
  "children4",
  "children24",
  "children224",
  "children2224",
  "children22224",
  "children222223"
)

function PlasmicItem__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(defaultcss.all, sty.section___5Kd0X)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container432"}
              data-plasmic-override={overrides.container432}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container432)}
            >
              <Button icons={"none"} slot={"Mens"}>
                <Icon24Icon
                  className={classNames(defaultcss.all, sty.svg__wswE9)}
                  role={"img"}
                />
              </Button>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__vmKg
                )}
              >
                {"/"}
              </div>

              <Button icons={"none"} slot={"Shoes"}>
                <Icon24Icon
                  className={classNames(defaultcss.all, sty.svg__gTvOn)}
                  role={"img"}
                />
              </Button>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__rnSaM
                )}
              >
                {"/"}
              </div>

              <Button icons={"none"} slot={"Running"}>
                <Icon24Icon
                  className={classNames(defaultcss.all, sty.svg__xLSq)}
                  role={"img"}
                />
              </Button>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__kmFcM)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container4322"}
              data-plasmic-override={overrides.container4322}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container4322)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__lBauq)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ryPh2)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={
                    "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/194681/02/sv01/fnd/PNA/fmt/png/Eternity-NITRO-Men's-Running-Shoes"
                  }
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__cmmq)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__mXAS)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/194681/02/mod03/fnd/PNA/fmt/png/Eternity-NITRO-Men's-Running-Shoes"
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___5G2Cy)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/194681/02/sv01/fnd/PNA/fmt/png/Eternity-NITRO-Men's-Running-Shoes"
                    }
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__woKY)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__d6YH3)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/194681/02/bv/fnd/PNA/fmt/png/Eternity-NITRO-Men's-Running-Shoes"
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__aehCi)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/194681/02/sv02/fnd/PNA/fmt/png/Eternity-NITRO-Men's-Running-Shoes"
                    }
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__keTyw)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__gjEu)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/194681/02/sv03/fnd/PNA/fmt/png/Eternity-NITRO-Men's-Running-Shoes"
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__wX4Fw)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/194681/02/sv04/fnd/PNA/fmt/png/Eternity-NITRO-Men's-Running-Shoes"
                    }
                  />
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__g1N0I)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text___4LgP
                  )}
                >
                  {"Eternity NITRO Men's Running Shoes"}
                </div>

                <Price
                  data-plasmic-name={"price"}
                  data-plasmic-override={overrides.price}
                  className={classNames("__wab_instance", sty.price)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___1WDiZ)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__wOcm)}
                    displayHeight={"64px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"64px"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_450,h_450/global/194681/03/sv01/fnd/PNA/fmt/png"
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__f0Izv)}
                    displayHeight={"64px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"64px"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_450,h_450/global/194681/01/sv01/fnd/PNA/fmt/png"
                    }
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__czCNj)}
                    displayHeight={"64px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"64px"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_450,h_450/global/194681/02/sv01/fnd/PNA/fmt/png"
                    }
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___3PIya)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__gQyOg
                    )}
                  >
                    {"Size"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__kiJqs)}
                  >
                    <Button
                      colors={"lightGrayOutline"}
                      icons={"none"}
                      slot={"7"}
                    />

                    <Button
                      colors={"lightGrayOutline"}
                      icons={"none"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__gzhwn
                          )}
                        >
                          {"7.5"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline"}
                      icons={"none"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__bPMiy
                          )}
                        >
                          {"8"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline"}
                      icons={"none"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__kjkTz
                          )}
                        >
                          {"8.5"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline"}
                      icons={"none"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text___8X3Md
                          )}
                        >
                          {"9"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline"}
                      icons={"none"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__cHlel
                          )}
                        >
                          {"9.5"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline"}
                      icons={"none"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__qCk86
                          )}
                        >
                          {"10"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline"}
                      icons={"none"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__o0BIp
                          )}
                        >
                          {"10.5"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline"}
                      icons={"none"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__fSrx
                          )}
                        >
                          {"11"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline"}
                      icons={"none"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__tuiu
                          )}
                        >
                          {"11.5"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline"}
                      icons={"none"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__z1Stc
                          )}
                        >
                          {"12"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline"}
                      icons={"none"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__hehKp
                          )}
                        >
                          {"13"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline"}
                      icons={"none"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__xyTj
                          )}
                        >
                          {"14"}
                        </div>
                      }
                    />
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___3VVAv)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__rd8Aw)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__jJwJl
                      )}
                    >
                      {"Quantity"}
                    </div>

                    <Button
                      children2={
                        <Icon25Icon
                          className={classNames(defaultcss.all, sty.svg__sTa2)}
                          role={"img"}
                        />
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.button__oQHwD
                      )}
                      colors={"lightGrayOutline"}
                      icons={"end"}
                      slot={"1"}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__d0Uyi)}
                  >
                    <Button
                      colors={"lightGrayOutline"}
                      icons={"only"}
                      size={"large"}
                      slot={"Add to cart"}
                    >
                      <Icon26Icon
                        className={classNames(defaultcss.all, sty.svg__rV9I7)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      colors={"black"}
                      icons={"none"}
                      link2={"/cart"}
                      rounded={"rounded"}
                      size={"large"}
                      slot={"Add to cart"}
                    />
                  </p.Stack>
                </p.Stack>

                <Separator
                  className={classNames("__wab_instance", sty.separator__ySc73)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__m7YxM)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__exaQp
                    )}
                  >
                    {"Description"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__sSlCw
                    )}
                  >
                    {
                      "Let Eternity NITRO be your guide. The engineered mesh upper integrates the runGUIDE tech, designed to hug your midfoot for an effortless ride. For the midsole, NITRO foam provides superior cushioning, combining with other tech elements to give you support: a TPU heel piece for proprioception, reflectivity, and a durable rubber PUMAGRIP for all-surface traction. You lead the way, Eternity NITRO will keep you in line."
                    }
                  </div>
                </p.Stack>

                <Separator
                  className={classNames("__wab_instance", sty.separator__wnRdB)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__hjktR)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__xTsXa
                    )}
                  >
                    {"Details"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__tULhi
                    )}
                  >
                    {"Adaptive fit with midfoot wrap for secure lockdown"}
                  </div>

                  <Separator
                    className={classNames("__wab_instance", sty.separator__qTB)}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__p8Vup
                    )}
                  >
                    {"Engineered mesh upper for support"}
                  </div>

                  <Separator
                    className={classNames(
                      "__wab_instance",
                      sty.separator__zegdX
                    )}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__cqjdz
                    )}
                  >
                    {"Full lace closure for snug fit"}
                  </div>

                  <Separator
                    className={classNames(
                      "__wab_instance",
                      sty.separator__fbxRi
                    )}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__z56Le
                    )}
                  >
                    {
                      "NITRO FOAM midsole for lightweight, responsive cushioning"
                    }
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__buNz)}>
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(defaultcss.all, sty.container42)}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(defaultcss.all, sty.freeBox___40Yw)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__t9S7N
                      )}
                    >
                      {"You may also like"}
                    </div>

                    <Button
                      children2={
                        <Icon5Icon
                          className={classNames(defaultcss.all, sty.svg__ugdzs)}
                          role={"img"}
                        />
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.button__z2G80
                      )}
                      icons={"end"}
                      link={"link"}
                      slot={"See more"}
                    />
                  </div>
                ),

                value: args.container42,
              })}
            </div>

            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(defaultcss.all, sty.container5)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__v4Jva)}
              >
                <ProductCard
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__qvP8Z)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/1070aebbb55841e1aae5ac9f00b39879_9366/adidas_Ultraboost_DNA_x_LEGO(r)_Plates_Shoes_White_FY7690_01_standard.jpg"
                        }
                      />
                    ),

                    value: args.children4,
                  })}
                  link={"http://google.com"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___6WrwG
                    )}
                  >
                    {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__u0T54
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__tSBxq
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__pche1)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/79d40e0b-da9d-4049-a4be-6a8fe7d9489e/air-zoom-pegasus-38-womens-running-shoe-2bvJvW.png"
                        }
                      />
                    ),

                    value: args.children24,
                  })}
                  link={"/item"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__u8Kw
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ahYl9
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___7ZSzU
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__rMu74)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={
                          "https://assets.reebok.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/3108369a42714ba6a9c2aa99017b457a_9366/Club_C_85_Vintage_Men's_Shoes_White_V67899_01_standard.jpg"
                        }
                      />
                    ),

                    value: args.children224,
                  })}
                  link={"/item"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__nxPjo
                    )}
                  >
                    {"Club C 85 Vintage Men's Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___0JLxH
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___95Kzc
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__nyAwA)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/b13d4f77-9404-492f-b2c8-5f06419f2cb6/air-max-genome-mens-shoe-hgsQFb.png"
                        }
                      />
                    ),

                    value: args.children2224,
                  })}
                  link={"/item"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__yRwwq
                    )}
                  >
                    {"Nike Air Max Genome"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__hzyVm
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__iF0Pb
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__h1Oc7)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/cdfdf1409e054322b9e0ac6d011da5e2_9366/Ultraboost_DNA_1.0_Shoes_Green_H05264_01_standard.jpg"
                        }
                      />
                    ),

                    value: args.children22224,
                  })}
                  link={"/item"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___48CiA
                    )}
                  >
                    {"ULTRABOOST DNA 1.0 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ilihO
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___7BzO
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___3JXa)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/f6cbde42-eed6-42bd-b5d9-1b5bef129618/zion-1-big-kids-shoe-BsvRq7.png"
                        }
                      />
                    ),

                    value: args.children222223,
                  })}
                  link={"/item"}
                />
              </p.Stack>
            </div>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
            container432={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___5JMcg)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__co5EM
                    )}
                  >
                    {"Subscribe"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__wl34R
                    )}
                  >
                    {
                      "Sign up for exclusive offers, original stories, activism, events and more."
                    }
                  </div>

                  <input
                    data-plasmic-name={"textbox"}
                    data-plasmic-override={overrides.textbox}
                    className={classNames(defaultcss.input, sty.textbox)}
                    placeholder={"Email address…"}
                    size={1}
                    type={"text"}
                    value={""}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__g6Ma3)}
                    colors={"black"}
                    icons={"none"}
                    slot={"Sign me up"}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__ntPc4)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__hevEm
                    )}
                  >
                    {"Help"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__mgvuF)}
                  >
                    <Button slot={"Order status"}>
                      <Icon22Icon
                        className={classNames(defaultcss.all, sty.svg__rEpLz)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__ohl3W
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__vW35
                          )}
                        >
                          {"Returns and exchanges"}
                        </div>
                      }
                    >
                      <Icon21Icon
                        className={classNames(defaultcss.all, sty.svg__x4YV6)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__u6Hfq
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__qlzVz
                          )}
                        >
                          {"Help center"}
                        </div>
                      }
                    >
                      <Icon20Icon
                        className={classNames(defaultcss.all, sty.svg__jkxc9)}
                        role={"img"}
                      />
                    </Button>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__oIzig)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___4Xmff
                    )}
                  >
                    {"More info"}
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__jjnMu)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        defaultcss.all,
                        sty.freeBox___3RRIp
                      )}
                    >
                      <Button icons={"none"} slot={"Gift cards"} />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___4DaZm
                        )}
                        icons={"none"}
                        slot={"Find a store"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__tQkWu
                        )}
                        icons={"none"}
                        slot={"Careers"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__iR7Nv
                        )}
                        icons={"none"}
                        slot={"Sitemap"}
                      />
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__fnTk9)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__nRkI1
                        )}
                        icons={"none"}
                        slot={"Group sales"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___3C2H1
                        )}
                        icons={"none"}
                        slot={"Privacy policy"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__pCrRl
                        )}
                        icons={"none"}
                        slot={"Contact us"}
                      />
                    </p.Stack>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          />
        </div>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "container432",
    "container4322",
    "price",
    "container42",
    "container5",
    "footer",
    "textbox",
  ],

  navBar: ["navBar"],
  container432: ["container432"],
  container4322: ["container4322", "price"],
  price: ["price"],
  container42: ["container42"],
  container5: ["container5"],
  footer: ["footer", "textbox"],
  textbox: ["textbox"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicItem__ArgProps,
      internalVariantPropNames: PlasmicItem__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicItem__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicItem"
  } else {
    func.displayName = `PlasmicItem.${nodeName}`
  }
  return func
}

export const PlasmicItem = Object.assign(
  // Top-level PlasmicItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    container432: makeNodeComponent("container432"),
    container4322: makeNodeComponent("container4322"),
    price: makeNodeComponent("price"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    footer: makeNodeComponent("footer"),
    textbox: makeNodeComponent("textbox"),
    // Metadata about props expected for PlasmicItem
    internalVariantProps: PlasmicItem__VariantProps,
    internalArgProps: PlasmicItem__ArgProps,
  }
)

export default PlasmicItem
/* prettier-ignore-end */
