// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bL97kH9Dzecu8g2MxMGBSt
// Component: cajWlUKm1qYM
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import Button from "../../Button" // plasmic-import: EDRR_UWJpEhW/component
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css" // plasmic-import: bL97kH9Dzecu8g2MxMGBSt/projectcss
import * as sty from "./PlasmicValue.module.css" // plasmic-import: cajWlUKm1qYM/css
import Icon9Icon from "./icons/PlasmicIcon__Icon9" // plasmic-import: IsLW5-7O9gr-/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5" // plasmic-import: T-JTXcMDzEWg/icon

export const PlasmicValue__VariantProps = new Array(
  "topBottom",
  "center",
  "withButton"
)

export const PlasmicValue__ArgProps = new Array("children", "slot", "children2")

function PlasmicValue__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__center]: hasVariant(variants, "center", "center"),
        [sty.root__topBottom]: hasVariant(variants, "topBottom", "topBottom"),
        [sty.root__withButton]: hasVariant(
          variants,
          "withButton",
          "withButton"
        ),
      })}
    >
      <div
        className={classNames(defaultcss.all, sty.freeBox___8Afe2, {
          [sty.freeBox__center___8Afe22LWb6]: hasVariant(
            variants,
            "center",
            "center"
          ),

          [sty.freeBox__topBottom___8Afe2ONk6P]: hasVariant(
            variants,
            "topBottom",
            "topBottom"
          ),
        })}
      >
        <div className={classNames(defaultcss.all, sty.freeBox__mxmJ6)}>
          {p.renderPlasmicSlot({
            defaultContents: (
              <Icon9Icon
                className={classNames(defaultcss.all, sty.svg__wdv6E)}
                role={"img"}
              />
            ),

            value: args.slot,
          })}
        </div>
      </div>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox__ijGd5, {
          [sty.freeBox__center__ijGd52LWb6]: hasVariant(
            variants,
            "center",
            "center"
          ),

          [sty.freeBox__withButton__ijGd5U4Fo0]: hasVariant(
            variants,
            "withButton",
            "withButton"
          ),
        })}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__sj9AK
                )}
              >
                {"Worldwide Shipping"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__rrj0S
                )}
              >
                {"Special financing and earn rewards."}
              </div>
            </React.Fragment>
          ),

          value: args.children,
          className: classNames(sty.slotTargetChildren, {
            [sty.slotTargetChildren__center]: hasVariant(
              variants,
              "center",
              "center"
            ),
          }),
        })}
      </p.Stack>

      {(hasVariant(variants, "withButton", "withButton") ? true : false) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.freeBox__g8TLy, {
            [sty.freeBox__center__g8TLy2LWb6]: hasVariant(
              variants,
              "center",
              "center"
            ),

            [sty.freeBox__withButton__g8TLyu4Fo0]: hasVariant(
              variants,
              "withButton",
              "withButton"
            ),
          })}
        >
          {p.renderPlasmicSlot({
            defaultContents: (
              <Button
                children2={
                  <Icon5Icon
                    className={classNames(defaultcss.all, sty.svg___0UMiU)}
                    role={"img"}
                  />
                }
                className={classNames("__wab_instance", sty.button__mbtw, {
                  [sty.button__withButton__mbtWu4Fo0]: hasVariant(
                    variants,
                    "withButton",
                    "withButton"
                  ),
                })}
                colors={"black"}
                icons={"end"}
                rounded={"rounded"}
                size={"large"}
                slot={"Read our letter"}
              />
            ),

            value: args.children2,
            className: classNames(sty.slotTargetChildren2, {
              [sty.slotTargetChildren2__center]: hasVariant(
                variants,
                "center",
                "center"
              ),

              [sty.slotTargetChildren2__withButton]: hasVariant(
                variants,
                "withButton",
                "withButton"
              ),
            }),
          })}
        </p.Stack>
      ) : null}
    </p.Stack>
  )
}

const PlasmicDescendants = {
  root: ["root"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicValue__ArgProps,
      internalVariantPropNames: PlasmicValue__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicValue__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicValue"
  } else {
    func.displayName = `PlasmicValue.${nodeName}`
  }
  return func
}

export const PlasmicValue = Object.assign(
  // Top-level PlasmicValue renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicValue
    internalVariantProps: PlasmicValue__VariantProps,
    internalArgProps: PlasmicValue__ArgProps,
  }
)

export default PlasmicValue
/* prettier-ignore-end */
